### ISSUE TITLE
Адаптация данных

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/analyze_market_data#2]
я нашел где достать данные но не смог адаптировать их анализ так как структура разная. https://tinkoff.github.io/investAPI/get_history/ . Можете адаптировать код под работу с этими данными. буду очень благодарен.

**Comment by Liddel2019** [comment]
[BBG004S687W8_2023.zip](https://github.com/EIDiamond/analyze_market_data/files/13199363/BBG004S687W8_2023.zip)
[BBG004Z2RGW8_2023.zip](https://github.com/EIDiamond/analyze_market_data/files/13199364/BBG004Z2RGW8_2023.zip)
[BBG007N0Z367_2023.zip](https://github.com/EIDiamond/analyze_market_data/files/13199365/BBG007N0Z367_2023.zip)
[BBG012YQ6P43_2023.zip](https://github.com/EIDiamond/analyze_market_data/files/13199366/BBG012YQ6P43_2023.zip)
[BBG002458LF8_2023.zip](https://github.com/EIDiamond/analyze_market_data/files/13199367/BBG002458LF8_2023.zip)
Спасибо если поможете

**Comment by EIDiamond** [comment]
Добавили поддержку. 

[DATA_PROVIDER]
NAME=TinkoffHistoryData
ROOT_PATH - указывает на папку с файлами свечей. 

Чтобы работало по-старому надо сделать NAME=TinkoffDownloaded

Если захочется за пару лет, то надо в одну папку сложить файлы свечей за разные годы, а в FROM_DAYS указать отрицательное число - это аналог настройки ВСЕ данные, без фильтарции (это же работает и для TinkoffDownloaded).

**Comment by Liddel2019** [comment]
Спасибо!
