### ISSUE TITLE
Идея для улучшения пользовательского опыта

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/analyze_market_data#3]
Прошу добавить поддержку анализа не только скачанных данных, но и данных которые будут грузится из tinkoff api как это сделано в https://github.com/EIDiamond/trade_backtesting. Это очень упростит работу с данными. Заранее спасибо за ответ!

**Comment by EIDiamond** [comment]
Привет, Вы про метод get_all_candles в API?

 with Client(self.__token, app_name=self.__app_name) as client:
            for candle in client.get_all_candles

**Comment by Liddel2019** [comment]
Да, что бы можно было выбрать за сколько дней получить данные. Ну нужна проверка на лимиты апи по запросам что бы данные были полные. Спасибо за ответ!

**Comment by Liddel2019** [comment]
Это было бы очень удобно, не нужно скачивать данные потом перекидывать их, и анализировать, а сразу  все за одно действие.

**Comment by EIDiamond** [comment]
Добавили поддержку.

[DATA_PROVIDER]
NAME=TinkoffAPIGetAllCandles
[DATA_PROVIDER_SETTINGS]
TOKEN= токен к Tinkoff API

Теперь отдельная секция для настроек [DATA_PROVIDER_SETTINGS]
ROOT_PATH для остальных провайдеров теперь надо указвать в [DATA_PROVIDER_SETTINGS]
Например так: 
DATA_PROVIDER_SETTINGS]
ROOT_PATH=../../../raw_market_data

На счет лимитов, тут явного 100 % алгоритма нет. На сетевые ошибки добавлены 5 попыток с 1 секундой ожидания и для уменьшения нагрузки каждый день запрашивается отдельным запросом. Так же если что-то "упадет" при запросе, то упадет все выполнение. Надеюсь этого должно хватить. 

Вообще такой вариант плох тем, что данные загружаются в память и после теста \ расчета выгружаются, т.е. их для следующего прогона придется скачивать заново. Что на самом деле не очень хорошо и с этой точки зрения два предыдуших провайдера работают лучше.

**Comment by Liddel2019** [comment]
Спасибо огромное!
